# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28a00549745ce89b0a28a37c67b70da865e47908fab925ef99e4ebe93b3a6e92f1fe1cbeed438b57948bd1523b2b268858e4148b28ab07ca5690159e0b10053f

test:
  secret_key_base: 9d8b9608620bb7e4f1ca84565ded3d0ee58919cf5cdf0f68bfcd2feb3e69d4aefe432ae932df2ea256ae9eead314e71ac094ab8a8be8fcf9634a0bd82fed2141

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
